# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'UI_design.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.Label_input = QtWidgets.QLabel(self.centralwidget)
        self.Label_input.setObjectName("Label_input")
        self.verticalLayout_4.addWidget(self.Label_input)
        self.textBrowser_input = QtWidgets.QTextBrowser(self.centralwidget)
        self.textBrowser_input.setObjectName("textBrowser_input")
        self.verticalLayout_4.addWidget(self.textBrowser_input)
        self.verticalLayout_7.addLayout(self.verticalLayout_4)
        self.Button_trans = QtWidgets.QPushButton(self.centralwidget)
        self.Button_trans.setObjectName("Button_trans")
        self.verticalLayout_7.addWidget(self.Button_trans)
        self.verticalLayout_5 = QtWidgets.QVBoxLayout()
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.Label_pinyin = QtWidgets.QLabel(self.centralwidget)
        self.Label_pinyin.setObjectName("Label_pinyin")
        self.verticalLayout_5.addWidget(self.Label_pinyin)
        self.textBrowser_pinyin = QtWidgets.QTextBrowser(self.centralwidget)
        self.textBrowser_pinyin.setObjectName("textBrowser_pinyin")
        self.verticalLayout_5.addWidget(self.textBrowser_pinyin)
        self.verticalLayout_7.addLayout(self.verticalLayout_5)
        self.verticalLayout_6 = QtWidgets.QVBoxLayout()
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.Label_note = QtWidgets.QLabel(self.centralwidget)
        self.Label_note.setObjectName("Label_note")
        self.verticalLayout_6.addWidget(self.Label_note)
        self.textBrowser_note = QtWidgets.QTextBrowser(self.centralwidget)
        self.textBrowser_note.setObjectName("textBrowser_note")
        self.verticalLayout_6.addWidget(self.textBrowser_note)
        self.verticalLayout_7.addLayout(self.verticalLayout_6)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 22))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.Label_input.setText(_translate("MainWindow", "输入中文句子"))
        self.Button_trans.setText(_translate("MainWindow", "翻译"))
        self.Label_pinyin.setText(_translate("MainWindow", "加拼音并翻译"))
        self.Label_note.setText(_translate("MainWindow", "注解"))
